//Generated by ChatGPT
$(document).ready(function() {
    // Define the image order and captions
    var images = [
        'ipad.png',
        'sun.png',
        'appalachia.png',
        'appalachia.png', // Duplicate entry for Appalachia
        'cat-meme.png',
        'cat-meme.png',   // Duplicate entry for Cat Meme
        'ohio.png',
        'ohio.png',       // Duplicate entry for Ohio
        'pavement.png',
        'eclipse.png',
        'roots.png'
    ];

    var captions = [
        'I - iPad',
        'S - Sun',
        'A - Appalachia',
        'A x2 - Appalachia',
        'C - Cat Meme',
        'C x2 - Cat Meme',
        'O - Ohio',
        'O x2 - Ohio',
        'P - Pavement',
        'E - Eclipse',
        'R - Roots'
    ];

    var currentIndex = 0;

    // Function to update the image and caption
    function updateImage() {
        $('#slideshow-image').fadeOut(300, function() {
            $(this).attr('src', 'images/' + images[currentIndex]).fadeIn(300);
        });
        $('#caption').text(captions[currentIndex]);
    }

    // Event handler for the 'Previous' button
    $('#prev-btn').click(function() {
        currentIndex = (currentIndex > 0) ? currentIndex - 1 : images.length - 1;
        updateImage();
    });

    // Event handler for the 'Next' button
    $('#next-btn').click(function() {
        currentIndex = (currentIndex < images.length - 1) ? currentIndex + 1 : 0;
        updateImage();
    });
});
